// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: stoplist/stoplist.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddWordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Word          string                 `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddWordRequest) Reset() {
	*x = AddWordRequest{}
	mi := &file_stoplist_stoplist_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddWordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddWordRequest) ProtoMessage() {}

func (x *AddWordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stoplist_stoplist_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddWordRequest.ProtoReflect.Descriptor instead.
func (*AddWordRequest) Descriptor() ([]byte, []int) {
	return file_stoplist_stoplist_proto_rawDescGZIP(), []int{0}
}

func (x *AddWordRequest) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

type DeleteWordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Word          string                 `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWordRequest) Reset() {
	*x = DeleteWordRequest{}
	mi := &file_stoplist_stoplist_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWordRequest) ProtoMessage() {}

func (x *DeleteWordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stoplist_stoplist_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWordRequest.ProtoReflect.Descriptor instead.
func (*DeleteWordRequest) Descriptor() ([]byte, []int) {
	return file_stoplist_stoplist_proto_rawDescGZIP(), []int{1}
}

func (x *DeleteWordRequest) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

var File_stoplist_stoplist_proto protoreflect.FileDescriptor

const file_stoplist_stoplist_proto_rawDesc = "" +
	"\n" +
	"\x17stoplist/stoplist.proto\x12\x0fstoplistservice\x1a\x1bgoogle/protobuf/empty.proto\"$\n" +
	"\x0eAddWordRequest\x12\x12\n" +
	"\x04word\x18\x01 \x01(\tR\x04word\"'\n" +
	"\x11DeleteWordRequest\x12\x12\n" +
	"\x04word\x18\x01 \x01(\tR\x04word2\x9f\x01\n" +
	"\x0fStopListService\x12B\n" +
	"\aAddWord\x12\x1f.stoplistservice.AddWordRequest\x1a\x16.google.protobuf.Empty\x12H\n" +
	"\n" +
	"DeleteWord\x12\".stoplistservice.DeleteWordRequest\x1a\x16.google.protobuf.EmptyBHZFgithub.com/wildberries-test-task-22-05-2026/internal/transport/grpc/pbb\x06proto3"

var (
	file_stoplist_stoplist_proto_rawDescOnce sync.Once
	file_stoplist_stoplist_proto_rawDescData []byte
)

func file_stoplist_stoplist_proto_rawDescGZIP() []byte {
	file_stoplist_stoplist_proto_rawDescOnce.Do(func() {
		file_stoplist_stoplist_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stoplist_stoplist_proto_rawDesc), len(file_stoplist_stoplist_proto_rawDesc)))
	})
	return file_stoplist_stoplist_proto_rawDescData
}

var file_stoplist_stoplist_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_stoplist_stoplist_proto_goTypes = []any{
	(*AddWordRequest)(nil),    // 0: stoplistservice.AddWordRequest
	(*DeleteWordRequest)(nil), // 1: stoplistservice.DeleteWordRequest
	(*emptypb.Empty)(nil),     // 2: google.protobuf.Empty
}
var file_stoplist_stoplist_proto_depIdxs = []int32{
	0, // 0: stoplistservice.StopListService.AddWord:input_type -> stoplistservice.AddWordRequest
	1, // 1: stoplistservice.StopListService.DeleteWord:input_type -> stoplistservice.DeleteWordRequest
	2, // 2: stoplistservice.StopListService.AddWord:output_type -> google.protobuf.Empty
	2, // 3: stoplistservice.StopListService.DeleteWord:output_type -> google.protobuf.Empty
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_stoplist_stoplist_proto_init() }
func file_stoplist_stoplist_proto_init() {
	if File_stoplist_stoplist_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stoplist_stoplist_proto_rawDesc), len(file_stoplist_stoplist_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stoplist_stoplist_proto_goTypes,
		DependencyIndexes: file_stoplist_stoplist_proto_depIdxs,
		MessageInfos:      file_stoplist_stoplist_proto_msgTypes,
	}.Build()
	File_stoplist_stoplist_proto = out.File
	file_stoplist_stoplist_proto_goTypes = nil
	file_stoplist_stoplist_proto_depIdxs = nil
}
