// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: stoplist/stoplist.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StopListService_AddWord_FullMethodName     = "/stoplistservice.StopListService/AddWord"
	StopListService_DeleteWord_FullMethodName  = "/stoplistservice.StopListService/DeleteWord"
	StopListService_GetAllWords_FullMethodName = "/stoplistservice.StopListService/GetAllWords"
)

// StopListServiceClient is the client API for StopListService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StopListServiceClient interface {
	AddWord(ctx context.Context, in *AddWordRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DeleteWord(ctx context.Context, in *DeleteWordRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetAllWords(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetAllWordsResponse, error)
}

type stopListServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStopListServiceClient(cc grpc.ClientConnInterface) StopListServiceClient {
	return &stopListServiceClient{cc}
}

func (c *stopListServiceClient) AddWord(ctx context.Context, in *AddWordRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, StopListService_AddWord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stopListServiceClient) DeleteWord(ctx context.Context, in *DeleteWordRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, StopListService_DeleteWord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stopListServiceClient) GetAllWords(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetAllWordsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllWordsResponse)
	err := c.cc.Invoke(ctx, StopListService_GetAllWords_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StopListServiceServer is the server API for StopListService service.
// All implementations must embed UnimplementedStopListServiceServer
// for forward compatibility.
type StopListServiceServer interface {
	AddWord(context.Context, *AddWordRequest) (*emptypb.Empty, error)
	DeleteWord(context.Context, *DeleteWordRequest) (*emptypb.Empty, error)
	GetAllWords(context.Context, *emptypb.Empty) (*GetAllWordsResponse, error)
	mustEmbedUnimplementedStopListServiceServer()
}

// UnimplementedStopListServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStopListServiceServer struct{}

func (UnimplementedStopListServiceServer) AddWord(context.Context, *AddWordRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method AddWord not implemented")
}
func (UnimplementedStopListServiceServer) DeleteWord(context.Context, *DeleteWordRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteWord not implemented")
}
func (UnimplementedStopListServiceServer) GetAllWords(context.Context, *emptypb.Empty) (*GetAllWordsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllWords not implemented")
}
func (UnimplementedStopListServiceServer) mustEmbedUnimplementedStopListServiceServer() {}
func (UnimplementedStopListServiceServer) testEmbeddedByValue()                         {}

// UnsafeStopListServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StopListServiceServer will
// result in compilation errors.
type UnsafeStopListServiceServer interface {
	mustEmbedUnimplementedStopListServiceServer()
}

func RegisterStopListServiceServer(s grpc.ServiceRegistrar, srv StopListServiceServer) {
	// If the following call panics, it indicates UnimplementedStopListServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StopListService_ServiceDesc, srv)
}

func _StopListService_AddWord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddWordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StopListServiceServer).AddWord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StopListService_AddWord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StopListServiceServer).AddWord(ctx, req.(*AddWordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StopListService_DeleteWord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteWordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StopListServiceServer).DeleteWord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StopListService_DeleteWord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StopListServiceServer).DeleteWord(ctx, req.(*DeleteWordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StopListService_GetAllWords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StopListServiceServer).GetAllWords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StopListService_GetAllWords_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StopListServiceServer).GetAllWords(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// StopListService_ServiceDesc is the grpc.ServiceDesc for StopListService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StopListService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "stoplistservice.StopListService",
	HandlerType: (*StopListServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddWord",
			Handler:    _StopListService_AddWord_Handler,
		},
		{
			MethodName: "DeleteWord",
			Handler:    _StopListService_DeleteWord_Handler,
		},
		{
			MethodName: "GetAllWords",
			Handler:    _StopListService_GetAllWords_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "stoplist/stoplist.proto",
}
