// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: trend/v1/trend.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TrendItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrendItem) Reset() {
	*x = TrendItem{}
	mi := &file_trend_v1_trend_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrendItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrendItem) ProtoMessage() {}

func (x *TrendItem) ProtoReflect() protoreflect.Message {
	mi := &file_trend_v1_trend_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrendItem.ProtoReflect.Descriptor instead.
func (*TrendItem) Descriptor() ([]byte, []int) {
	return file_trend_v1_trend_proto_rawDescGZIP(), []int{0}
}

func (x *TrendItem) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *TrendItem) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GetTopNRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopNRequest) Reset() {
	*x = GetTopNRequest{}
	mi := &file_trend_v1_trend_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopNRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopNRequest) ProtoMessage() {}

func (x *GetTopNRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trend_v1_trend_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopNRequest.ProtoReflect.Descriptor instead.
func (*GetTopNRequest) Descriptor() ([]byte, []int) {
	return file_trend_v1_trend_proto_rawDescGZIP(), []int{1}
}

func (x *GetTopNRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetTopNResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Trends        []*TrendItem           `protobuf:"bytes,1,rep,name=trends,proto3" json:"trends,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopNResponse) Reset() {
	*x = GetTopNResponse{}
	mi := &file_trend_v1_trend_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopNResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopNResponse) ProtoMessage() {}

func (x *GetTopNResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trend_v1_trend_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopNResponse.ProtoReflect.Descriptor instead.
func (*GetTopNResponse) Descriptor() ([]byte, []int) {
	return file_trend_v1_trend_proto_rawDescGZIP(), []int{2}
}

func (x *GetTopNResponse) GetTrends() []*TrendItem {
	if x != nil {
		return x.Trends
	}
	return nil
}

var File_trend_v1_trend_proto protoreflect.FileDescriptor

const file_trend_v1_trend_proto_rawDesc = "" +
	"\n" +
	"\x14trend/v1/trend.proto\x12\ftrendservice\"7\n" +
	"\tTrendItem\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"&\n" +
	"\x0eGetTopNRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"B\n" +
	"\x0fGetTopNResponse\x12/\n" +
	"\x06trends\x18\x01 \x03(\v2\x17.trendservice.TrendItemR\x06trends2V\n" +
	"\fTrendService\x12F\n" +
	"\aGetTopN\x12\x1c.trendservice.GetTopNRequest\x1a\x1d.trendservice.GetTopNResponseBHZFgithub.com/wildberries-test-task-22-05-2026/internal/transport/grpc/pbb\x06proto3"

var (
	file_trend_v1_trend_proto_rawDescOnce sync.Once
	file_trend_v1_trend_proto_rawDescData []byte
)

func file_trend_v1_trend_proto_rawDescGZIP() []byte {
	file_trend_v1_trend_proto_rawDescOnce.Do(func() {
		file_trend_v1_trend_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_trend_v1_trend_proto_rawDesc), len(file_trend_v1_trend_proto_rawDesc)))
	})
	return file_trend_v1_trend_proto_rawDescData
}

var file_trend_v1_trend_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_trend_v1_trend_proto_goTypes = []any{
	(*TrendItem)(nil),       // 0: trendservice.TrendItem
	(*GetTopNRequest)(nil),  // 1: trendservice.GetTopNRequest
	(*GetTopNResponse)(nil), // 2: trendservice.GetTopNResponse
}
var file_trend_v1_trend_proto_depIdxs = []int32{
	0, // 0: trendservice.GetTopNResponse.trends:type_name -> trendservice.TrendItem
	1, // 1: trendservice.TrendService.GetTopN:input_type -> trendservice.GetTopNRequest
	2, // 2: trendservice.TrendService.GetTopN:output_type -> trendservice.GetTopNResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_trend_v1_trend_proto_init() }
func file_trend_v1_trend_proto_init() {
	if File_trend_v1_trend_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_trend_v1_trend_proto_rawDesc), len(file_trend_v1_trend_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_trend_v1_trend_proto_goTypes,
		DependencyIndexes: file_trend_v1_trend_proto_depIdxs,
		MessageInfos:      file_trend_v1_trend_proto_msgTypes,
	}.Build()
	File_trend_v1_trend_proto = out.File
	file_trend_v1_trend_proto_goTypes = nil
	file_trend_v1_trend_proto_depIdxs = nil
}
