// Code generated by MockGen. DO NOT EDIT.
// Source: trend.go
//
// Generated by this command:
//
//	mockgen -source=trend.go -destination=mocks/mock_trend.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/wildberries-test-task-22-05-2026/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockTrendRepository is a mock of TrendRepository interface.
type MockTrendRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTrendRepositoryMockRecorder
	isgomock struct{}
}

// MockTrendRepositoryMockRecorder is the mock recorder for MockTrendRepository.
type MockTrendRepositoryMockRecorder struct {
	mock *MockTrendRepository
}

// NewMockTrendRepository creates a new mock instance.
func NewMockTrendRepository(ctrl *gomock.Controller) *MockTrendRepository {
	mock := &MockTrendRepository{ctrl: ctrl}
	mock.recorder = &MockTrendRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTrendRepository) EXPECT() *MockTrendRepositoryMockRecorder {
	return m.recorder
}

// AddSearchEvent mocks base method.
func (m *MockTrendRepository) AddSearchEvent(ctx context.Context, event domain.SearchEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddSearchEvent", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddSearchEvent indicates an expected call of AddSearchEvent.
func (mr *MockTrendRepositoryMockRecorder) AddSearchEvent(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddSearchEvent", reflect.TypeOf((*MockTrendRepository)(nil).AddSearchEvent), ctx, event)
}

// GetTopNTrends mocks base method.
func (m *MockTrendRepository) GetTopNTrends(ctx context.Context, n int) ([]domain.TrendQuery, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTopNTrends", ctx, n)
	ret0, _ := ret[0].([]domain.TrendQuery)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTopNTrends indicates an expected call of GetTopNTrends.
func (mr *MockTrendRepositoryMockRecorder) GetTopNTrends(ctx, n any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTopNTrends", reflect.TypeOf((*MockTrendRepository)(nil).GetTopNTrends), ctx, n)
}

// MockStopListChecker is a mock of StopListChecker interface.
type MockStopListChecker struct {
	ctrl     *gomock.Controller
	recorder *MockStopListCheckerMockRecorder
	isgomock struct{}
}

// MockStopListCheckerMockRecorder is the mock recorder for MockStopListChecker.
type MockStopListCheckerMockRecorder struct {
	mock *MockStopListChecker
}

// NewMockStopListChecker creates a new mock instance.
func NewMockStopListChecker(ctrl *gomock.Controller) *MockStopListChecker {
	mock := &MockStopListChecker{ctrl: ctrl}
	mock.recorder = &MockStopListCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStopListChecker) EXPECT() *MockStopListCheckerMockRecorder {
	return m.recorder
}

// IsBlocked mocks base method.
func (m *MockStopListChecker) IsBlocked(ctx context.Context, query string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsBlocked", ctx, query)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsBlocked indicates an expected call of IsBlocked.
func (mr *MockStopListCheckerMockRecorder) IsBlocked(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsBlocked", reflect.TypeOf((*MockStopListChecker)(nil).IsBlocked), ctx, query)
}
