// Code generated by MockGen. DO NOT EDIT.
// Source: stoplist.go
//
// Generated by this command:
//
//	mockgen -source=stoplist.go -destination=mocks/mock_stoplist.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockStopListRepository is a mock of StopListRepository interface.
type MockStopListRepository struct {
	ctrl     *gomock.Controller
	recorder *MockStopListRepositoryMockRecorder
	isgomock struct{}
}

// MockStopListRepositoryMockRecorder is the mock recorder for MockStopListRepository.
type MockStopListRepositoryMockRecorder struct {
	mock *MockStopListRepository
}

// NewMockStopListRepository creates a new mock instance.
func NewMockStopListRepository(ctrl *gomock.Controller) *MockStopListRepository {
	mock := &MockStopListRepository{ctrl: ctrl}
	mock.recorder = &MockStopListRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStopListRepository) EXPECT() *MockStopListRepositoryMockRecorder {
	return m.recorder
}

// AddWord mocks base method.
func (m *MockStopListRepository) AddWord(ctx context.Context, word string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddWord", ctx, word)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddWord indicates an expected call of AddWord.
func (mr *MockStopListRepositoryMockRecorder) AddWord(ctx, word any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddWord", reflect.TypeOf((*MockStopListRepository)(nil).AddWord), ctx, word)
}

// DeleteWord mocks base method.
func (m *MockStopListRepository) DeleteWord(ctx context.Context, word string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteWord", ctx, word)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteWord indicates an expected call of DeleteWord.
func (mr *MockStopListRepositoryMockRecorder) DeleteWord(ctx, word any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWord", reflect.TypeOf((*MockStopListRepository)(nil).DeleteWord), ctx, word)
}

// GetAllWords mocks base method.
func (m *MockStopListRepository) GetAllWords(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllWords", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllWords indicates an expected call of GetAllWords.
func (mr *MockStopListRepositoryMockRecorder) GetAllWords(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllWords", reflect.TypeOf((*MockStopListRepository)(nil).GetAllWords), ctx)
}

// IsBlocked mocks base method.
func (m *MockStopListRepository) IsBlocked(ctx context.Context, token string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsBlocked", ctx, token)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsBlocked indicates an expected call of IsBlocked.
func (mr *MockStopListRepositoryMockRecorder) IsBlocked(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsBlocked", reflect.TypeOf((*MockStopListRepository)(nil).IsBlocked), ctx, token)
}
