// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package kafka

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonEa312aa0DecodeGithubComWildberriesTestTask22052026InternalTransportKafka(in *jlexer.Lexer, out *SearchEventPayload) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "session_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SessionID = string(in.String())
			}
		case "timestamp":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Timestamp = int64(in.Int64())
			}
		case "normalized_query":
			if in.IsNull() {
				in.Skip()
			} else {
				out.NormalizedQuery = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonEa312aa0EncodeGithubComWildberriesTestTask22052026InternalTransportKafka(out *jwriter.Writer, in SearchEventPayload) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"session_id\":"
		out.RawString(prefix[1:])
		out.String(string(in.SessionID))
	}
	{
		const prefix string = ",\"timestamp\":"
		out.RawString(prefix)
		out.Int64(int64(in.Timestamp))
	}
	{
		const prefix string = ",\"normalized_query\":"
		out.RawString(prefix)
		out.String(string(in.NormalizedQuery))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v SearchEventPayload) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonEa312aa0EncodeGithubComWildberriesTestTask22052026InternalTransportKafka(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SearchEventPayload) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonEa312aa0EncodeGithubComWildberriesTestTask22052026InternalTransportKafka(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *SearchEventPayload) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonEa312aa0DecodeGithubComWildberriesTestTask22052026InternalTransportKafka(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SearchEventPayload) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonEa312aa0DecodeGithubComWildberriesTestTask22052026InternalTransportKafka(l, v)
}
